name: CI Pipeline

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building the project"

  test:
    runs-on: ubuntu-latest
    needs: build  # Depends on the build job
    steps:
      - run: echo "Running tests" && exit 1

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Depends on the test job
    steps:
      - run: echo "Deploying the project"
